version: "1.0"
info:
  model: int-scaffold
packages:
- name: JcDemoProject
  gitServerName: johnpcarter
  gitUrl: https://github.com/johnpcarter
  gitUsername: johnpcarter
  gitBranch: main
- name: JcPublicTools
  version: "5.0"
  gitServerName: johnpcarter
  gitUrl: https://github.com/johnpcarter
  gitUsername: johnpcarter
  gitTag: v2.1.0
security:
- name: JcPublicTools
  allowedServices:
  - jc.tools.pub.date:currentYear
  javaServiceSetting: RESTRICTED
services:
- serviceName: project.jcdemo.integrations:getCurrentYearFromPublicPackage
  packages:
  - name: JcDemoProject
    version: "1.0"
  - name: JcPublicTools
    version: "5.0"
- serviceName: jc.tools.pub.date:currentYear
  packages:
  - name: JcPublicTools
    version: "5.0"
