version: "1.0"
info:
  model: int-scaffold
packages:
- name: JcDemoProject
  gitServerName: johnpcarter
  gitUrl: https://github.com/johnpcarter
  gitUsername: johnpcarter
  gitBranch: main
- name: JcPublicTools
  gitServerName: johnpcarter
  gitUrl: https://github.com/johnpcarter
  gitUsername: johnpcarter
  gitTag: v2.1.0
